---
name: Build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [created]
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: python setup.py test

      - name: Backstage entity validator
        uses: RoadieHQ/backstage-entity-validator@v0.3.11
